
model_config:
  max_seq_length: 1048 # Choose any! We auto support RoPE Scaling internally!

training:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 2

  warmup_steps: 10
  max_steps: 50
  # warmup_ratio = 0.1,
  # num_train_epochs: 1


    # Select a 2 to 10x smaller learning rate for the embedding matrices!
  learning_rate: 5e-5
  embedding_learning_rate: 1e-5

  save_steps: 10
  save_total_limit: 2

  logging_steps: 1
  optim: "adamw_8bit"
  weight_decay: 0.001
  lr_scheduler_type: "linear"
  seed: 3407
  report_to: "wandb" # Use TrackIO/WandB etc

 

dataset:
  name: "wikimedia/wikipedia"
  language: "20231101.ur"
  split: "train[:1%]"


paths:
  output_dir: "Aqal-1.0-1.5B-instruct-lora-checkpoints"
  final_model_local_save_dir_name: "Aqal-1.0-1.5B-instruct-lora" # Aql‑1.0‑7B‑Base
  final_model_hub_save_dir_name: "Aqal-1.0-1.5B-instruct-lora" # Aql‑1.0‑7B‑Base
